# Generated by Django 5.0.1 on 2026-01-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('REDDIT', 'Reddit')], max_length=20)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('fetch_frequency', models.IntegerField(default=30, help_text='Fetch frequency in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('published_date', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(default=0, help_text='Reddit score/votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.newssource')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='news_newsar_publish_efb9f8_idx'), models.Index(fields=['source', '-published_date'], name='news_newsar_source__16e1b8_idx')],
            },
        ),
    ]
