# Generated by Django 5.0.1 on 2026-01-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tutorial_url',
            field=models.URLField(blank=True, help_text='Link to tutorial or usage guide'),
        ),
    ]
