# Generated by Django 5.0.1 on 2026-01-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('tools', '0002_tool_tutorial_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('estimated_hours', models.IntegerField(help_text='Estimated completion time in hours')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('estimated_hours', models.IntegerField(help_text='Hours to complete this skill')),
                ('order', models.IntegerField(default=0, help_text='Display order in tree')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certifications', models.ManyToManyField(blank=True, help_text='Certifications that test this skill', related_name='skill_nodes', to='resources.certification')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning_paths.learningpath')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Skills that must be completed before this one', related_name='unlocks', to='learning_paths.skillnode')),
                ('resources', models.ManyToManyField(blank=True, help_text='Learning resources for this skill', related_name='skill_nodes', to='resources.resource')),
                ('tools', models.ManyToManyField(blank=True, help_text='Tools to practice this skill', related_name='skill_nodes', to='tools.tool')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('learning_path', 'slug')},
            },
        ),
    ]
