# Generated by Django 5.0.1 on 2026-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillnode',
            name='learning_resources',
            field=models.JSONField(blank=True, default=list, help_text="List of curated learning resources: [{'title': '...', 'url': '...', 'type': 'video|article|course|tutorial|book|documentation', 'description': '...'}]"),
        ),
    ]
