# Generated by Django 5.0.1 on 2026-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVESearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, null=True)),
                ('affected_products', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['cve_id'], name='cve_cve_cve_id_849359_idx'), models.Index(fields=['-published_date'], name='cve_cve_publish_c65c7b_idx')],
            },
        ),
    ]
